{% set name = "uranography" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uranography-{{ version }}.tar.gz
  sha256: cb3b81e5868a86a55496781b6f44df0f7acbec9e49243f5b411ce24dee673acd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas
    - astropy >=5.3
    - healpy
    - healsparse
    - bokeh >=3.1.1
    - panel >=1.1.0
    - colorcet
    - jupyter
    - nbconvert
    - selenium

test:
  imports:
    - uranography
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lsst/uranography
  summary: Tools for visualization of the celestial sphere.
  doc_url: https://uranography.lsst.io
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - COPYRIGHT

extra:
  recipe-maintainers:
    - rhiannonlynne
    - ehneilsen
